name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:main
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - uses: actions/checkout@v4
      - name: Initialize west
        run: |
          west init -l .
          west update
      - name: Build firmware nrf52840dk_nrf52840
        run: |
          west build -d build-nrf52840dk_nrf52840 -b nrf52840dk/nrf52840 app
      - name: Build firmware holyiot_yj17095
        run: |
          west build -d build-holyiot_yj17095 -b holyiot_yj17095 app
      - name: Archive firmware nrf52840dk_nrf52840
        uses: actions/upload-artifact@v4
        with:
          name: firmware_nrf52840dk_nrf52840
          path: build-nrf52840dk_nrf52840/zephyr/*.hex
      - name: Archive firmware holyiot_yj17095
        uses: actions/upload-artifact@v4
        with:
          name: firmware_holyiot_yj17095
          path: build-holyiot_yj17095/zephyr/*.hex
